# File managed by pluginsync
sudo: false
language: go
go:
- 1.6.3
- 1.7.1
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: ZuSvtE+s/5iXFAuSPEy0VpP/fOGrV+3jxPkYs6l3+1fYxolTOilRbGPXjNGYvcGBlM6Yti6CCq980o8+zAPQt0ZxHwo1eeBBXGQGRIhfE5+w2MZShxLqj0XYDf3DRIUYMUq4WODhgRgUwPP0+W7Mc3lGkewyCV48wKH+Ayp4yQZwJP1TLtP7Tks9/vr/UPG/IjOJ898De5O1hwRJ/763i0Fgj34OdFmHJkBuSKrMTCS3H9rwq0WHZR0sdHgndnqV4Zw8bhg/XSetNZlYjfhWs1K77YHVV/XPOwusW4H4+HmkIx4VCmMF7QbjjrG/+rrbmusGOBIizNyWFRukN4t8an6jlHmubcDE//+c/IT5dtADgLbFz+CBHP22G4hLE+CfPxlsJ/m2zvac19zRimIWF+PBt0f5kdzvKKbu0NMQjbut+E61PZI2/csfi3QfxFDw4svvv79vwdoEScB5pFpOCOtAIaFz5+foBJFdScYCJmtnU57w9hJP/ffs00pgpgpOmCN/iMxo5gW/RtBq1Ev3uN1uFDESq43htas142huqT9DLrdpF3T4ljeARzlOLxYqJCQ38KP6JSk9XdsspAWgpxiS0EaFHky1ozndVUjyTqhuy4AKyOOs6Tb1vZO/lnS0Qvp+ebq+ibpsHHmG6C5oyfNOLYN53WZV4ed/Vds/m7Y=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-node-manager
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: ZuSvtE+s/5iXFAuSPEy0VpP/fOGrV+3jxPkYs6l3+1fYxolTOilRbGPXjNGYvcGBlM6Yti6CCq980o8+zAPQt0ZxHwo1eeBBXGQGRIhfE5+w2MZShxLqj0XYDf3DRIUYMUq4WODhgRgUwPP0+W7Mc3lGkewyCV48wKH+Ayp4yQZwJP1TLtP7Tks9/vr/UPG/IjOJ898De5O1hwRJ/763i0Fgj34OdFmHJkBuSKrMTCS3H9rwq0WHZR0sdHgndnqV4Zw8bhg/XSetNZlYjfhWs1K77YHVV/XPOwusW4H4+HmkIx4VCmMF7QbjjrG/+rrbmusGOBIizNyWFRukN4t8an6jlHmubcDE//+c/IT5dtADgLbFz+CBHP22G4hLE+CfPxlsJ/m2zvac19zRimIWF+PBt0f5kdzvKKbu0NMQjbut+E61PZI2/csfi3QfxFDw4svvv79vwdoEScB5pFpOCOtAIaFz5+foBJFdScYCJmtnU57w9hJP/ffs00pgpgpOmCN/iMxo5gW/RtBq1Ev3uN1uFDESq43htas142huqT9DLrdpF3T4ljeARzlOLxYqJCQ38KP6JSk9XdsspAWgpxiS0EaFHky1ozndVUjyTqhuy4AKyOOs6Tb1vZO/lnS0Qvp+ebq+ibpsHHmG6C5oyfNOLYN53WZV4ed/Vds/m7Y=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-node-manager
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: releases
  api_key:
    secure: d9AACtEUmKpeNlKxqNCIxJe2ycOyFnJUMu9CZ9raKywOgBEy7XfZ2WoaMEpuT9+mhfgstZe5Unj67RVjL+VkwW6AjaVkHTtBK2cQKjEmUQxLonrRsQnDwc4kx1u7SeHfrz3yrJWSvpsbyXH+UbS0rHrgU1Jksb//JVlP67ryrw6BiUaicYvhJeO4gb5haJX2BtTt/ksF9AiuUaKFK2qN6W0L+rWv4pQKZx/atsw+/mdjU3jagOgZu4tT0l+qo02urbYDIUYaU/qMB7Ug/DuCvTgwtaU6O1olGwkVZ/3aUgsuOIEyvof/bu+4AAaBJnIHU/wubPrfrTnIYYmS7b23teZ4p3HFhA3iUvLpgPETWHcUq/NrTkC2uEJOzq6RpLhm7WtLPxL9sZLv/pZGOv8vICwwiwq4H6WpCueOpB522f4ZauoTg+7CC52BhT4ESI/oNCv2Mv5wUQoncburfXS/91K3SIHRFllFv/2pdL60x2nKW08UdcsojscJlGCt3R9BAtFwaKRfuzmB6mouKcmIL2xlgwpw45q+XOuytcDjuuhsXFXtk3mJRVYXhOtVuFf7Jx0ipb1egqOZ74P3RG8nb7js6nVQNSqZaPXVx92KJlHDydFlRhJUhBdvrlPr24MpwOl/ujVFoxlFFgGtx8Hv7QaSC0jssFx5GJrOxi/Y1w0=
  file:
    - release/snap-plugin-collector-node-manager_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-collector-node-manager
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
